version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=auth
    environment:
      - TARGET=auth
      - DB_URL=postgres://postgres:pass@192.168.1.182:5433/postgres
    networks:
      - my-network
    ports:
    - "3000:3000"

  token:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=token
    environment:
      - TARGET=token
      - DB_URL=postgres://postgres:pass@192.168.1.182:5433/postgres
      - AUTH_SECRET_KEY=access-secret-key
      - REFRESH_SECRET_KEY=refresh-secret-key
    networks:
      - my-network
    ports:
    - "3001:3000"

networks:
  my-network:
    driver: bridge