version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=auth
    environment:
      - TARGET=auth
      - AUTH_SECRET_KEY=access-secret-key
      - DB_URL=postgres://postgres:pass@192.168.1.182:5433/postgres
      - MONGO_URL=mongodb://mongo:pass@192.168.1.182:27018/
      - SERVER_SECRET_KEY=server-secret-key
    networks:
      - my-network
    ports:
    - "3000:3000"

  token:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=token
    environment:
      - TARGET=token
      - DB_URL=postgres://postgres:pass@192.168.1.182:5433/postgres
      - MONGO_URL=mongodb://mongo:pass@192.168.1.182:27018/
      - AUTH_SECRET_KEY=access-secret-key
      - REFRESH_SECRET_KEY=refresh-secret-key
      - SERVER_SECRET_KEY=server-secret-key
    networks:
      - my-network
    ports:
    - "3001:3000"

  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=admin
    environment:
      - TARGET=admin
      - DB_URL=postgres://postgres:pass@192.168.1.182:5433/postgres
      - MONGO_URL=mongodb://mongo:pass@192.168.1.182:27018/
    networks:
      - my-network
    ports:
      - "3002:3000"

networks:
  my-network:
    driver: bridge